repo_url: https://github.com/Requisitos-de-Software/2024.1-Grupo07
repo_name: 2024.1-Meu-INSS
site_url: https://github.com/Requisitos-de-Software/2024.1-Grupo07

site_name: Meu INSS
nav:
    - Inicio: "index.md"
    - Atas: 
        - Ata 01: "atas/Ata1.md"
theme:
  name: material
  logo: imagens/inss-logo.png
  features:
    - navigation.tabs
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: orange
      toggle:
        icon: material/eye
        name: Mudar para o modo escuro

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/eye-outline
        name: Mudar para o modo claro